I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 15, in script call
    $ Chapter(1).start()
  File "game/Chapters/ch_1.rpy", line 33, in script
    $ counter_testsilence += 1
  File "game/Chapters/ch_1.rpy", line 33, in <module>
    $ counter_testsilence += 1
NameError: name 'counter_testsilence' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 15, in script call
    $ Chapter(1).start()
  File "game/Chapters/ch_1.rpy", line 33, in script
    $ counter_testsilence += 1
  File "C:\Users\david.robson\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\david.robson\Desktop\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/Chapters/ch_1.rpy", line 33, in <module>
    $ counter_testsilence += 1
NameError: name 'counter_testsilence' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
The Archiver of Inkwell 1.0
Sun Jan 28 13:10:01 2024
